env: "local" # local, dev or prod

telegram:
  token: "telegram-token"

ollana:
  host: "http://ollama:11434"

postgres:
  host: "postgres"
  port: "5432"
  user: "kypidbot"
  name: "kypidbot"
  password: "kypidbot"
  sslmode: "disable"
